language: php

sudo: false

matrix:
  include:
    - php: 5.5.9
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
      dist: trusty

before_install:
  - cp .env.example .env
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ $TRAVIS_PHP_VERSION == hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini; fi

install: travis_retry composer install --no-interaction --no-suggest

notifications:
  email: false

script: vendor/bin/phpunit --verbose --debug
