on:
  schedule:
    - cron: '0 7 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
            uses: actions/checkout@v2

        - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
            php-version: '7.4'

        - name: Install dependencies
            run: composer install

        - name: Build API docs
            run: php vendor/bin/phpdoc -d src -t docs/api

        - name: Commit and push changes
            run: |
            git config --local user.email "
