name: Transfer Wrapper Issues

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  transfer:
    name: Transfer issue to core
    runs-on: ubuntu-latest
    steps:
      - name: Create Cachet Bot token
        id: cachet-bot-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.CACHET_BOT_APP_ID }}
          private-key: ${{ secrets.CACHET_BOT_PRIVATE_KEY }}
          owner: cachethq
          repositories: |-
            cachet
            core

      - name: Transfer issue
        env:
          GH_TOKEN: ${{ steps.cachet-bot-token.outputs.token }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: gh issue transfer "$ISSUE_URL" cachethq/core
